// <auto-generated />
using System;
using MergeCat.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MergeCat.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MergeCat.Models.Cell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("UnitLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unit_level");

                    b.HasKey("Id")
                        .HasName("pk_cells");

                    b.HasIndex("PlayerId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_cells_player_id_index");

                    b.ToTable("cells", (string)null);
                });

            modelBuilder.Entity("MergeCat.Models.MergeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CellAId")
                        .HasColumnType("uuid")
                        .HasColumnName("cell_a_id");

                    b.Property<Guid>("CellBId")
                        .HasColumnType("uuid")
                        .HasColumnName("cell_b_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("ResultingLevel")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_level");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_merge_logs");

                    b.HasIndex("CellAId")
                        .HasDatabaseName("ix_merge_logs_cell_a_id");

                    b.HasIndex("CellBId")
                        .HasDatabaseName("ix_merge_logs_cell_b_id");

                    b.ToTable("merge_logs", (string)null);
                });

            modelBuilder.Entity("MergeCat.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Balance")
                        .HasColumnType("double precision")
                        .HasColumnName("balance");

                    b.Property<double>("IncomeRate")
                        .HasColumnType("double precision")
                        .HasColumnName("income_rate");

                    b.Property<DateTime>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_collected_at");

                    b.Property<double>("TotalEarned")
                        .HasColumnType("double precision")
                        .HasColumnName("total_earned");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasColumnType("char(42)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("WalletAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_players_wallet_address");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("MergeCat.Models.Cell", b =>
                {
                    b.HasOne("MergeCat.Models.Player", "Player")
                        .WithMany("Cells")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cells_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MergeCat.Models.MergeLog", b =>
                {
                    b.HasOne("MergeCat.Models.Cell", "CellA")
                        .WithMany()
                        .HasForeignKey("CellAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merge_logs_cells_cell_a_id");

                    b.HasOne("MergeCat.Models.Cell", "CellB")
                        .WithMany()
                        .HasForeignKey("CellBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merge_logs_cells_cell_b_id");

                    b.Navigation("CellA");

                    b.Navigation("CellB");
                });

            modelBuilder.Entity("MergeCat.Models.Player", b =>
                {
                    b.Navigation("Cells");
                });
#pragma warning restore 612, 618
        }
    }
}
